name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행됨
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃 리포지토리
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Ruby, Bundler 설치
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 사용하려는 Ruby 버전 설정
          bundler-cache: true  # Bundler 캐시 활성화

      # 3. Jekyll 및 의존성 설치
      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # 4. 사이트 빌드
      - name: Build the site
        run: |
          bundle exec jekyll build

      # 5. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll 빌드된 파일들이 있는 디렉토리
